-- Durable audit trail for administrator actions.
-- Run this migration after the existing unified-schema migrations.

BEGIN;

CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id integer NOT NULL,
    admin_username text NOT NULL,
    action text NOT NULL,
    target_type text NOT NULL,
    target_id text NOT NULL,
    changes jsonb NOT NULL DEFAULT '{}'::jsonb,
    sync_channels boolean,
    ip_address text,
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_admin_id
    ON public.admin_audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_action
    ON public.admin_audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_target_type
    ON public.admin_audit_logs (target_type);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_target_id
    ON public.admin_audit_logs (target_id);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_created_at
    ON public.admin_audit_logs (created_at);

COMMENT ON TABLE public.admin_audit_logs IS
    'Durable audit records for administrator actions';

COMMIT;
