-- Migration 07.
-- Adds short-lived, single-use login tokens for the SNS bot login flow.
-- The bot requests a token on behalf of a Telegram user; the user pastes the
-- token into the website, which exchanges it for an SNS JWT.
--
-- Run against the unified production database (after migrations 01-06).

BEGIN;

DO $BODY$
BEGIN
    IF to_regclass('public.users_eurobot') IS NULL THEN
        RAISE EXCEPTION 'Migration stopped: public.users_eurobot does not exist';
    END IF;
END;
$BODY$;

CREATE TABLE IF NOT EXISTS public.sns_login_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL
                REFERENCES public.users_eurobot (user_id)
                ON DELETE CASCADE,

    -- SHA-256 hex digest of the issued token; the raw token never touches disk.
    token_hash  char(64) NOT NULL UNIQUE,

    expires_at  timestamptz NOT NULL,
    used_at     timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sns_login_tokens_user_id
    ON public.sns_login_tokens (user_id);

CREATE INDEX IF NOT EXISTS idx_sns_login_tokens_expires_at
    ON public.sns_login_tokens (expires_at);

COMMENT ON TABLE public.sns_login_tokens IS
    'Short-lived single-use tokens issued by the SNS bot for website login';

COMMIT;
