-- Migration 12.
-- Adds the core service-directory domain: services, a hierarchical category
-- tree, the service<->category many-to-many link (exactly one primary category
-- per service), and a flexible per-service contact list.
--
-- Additive only. Nothing on public.users_eurobot changes; services.owner_user_id
-- is an optional reference to an existing user identity, so a service may exist
-- with no owner. Deleting a user clears the reference instead of deleting the
-- listing (ON DELETE SET NULL).
--
-- Run against the unified production database (after migrations 01-11).

BEGIN;

-- ---------------------------------------------------------------------------
-- 0. Guard: the user table must exist, because services optionally reference it.
-- ---------------------------------------------------------------------------
DO $BODY$
BEGIN
    IF to_regclass('public.users_eurobot') IS NULL THEN
        RAISE EXCEPTION 'Migration stopped: public.users_eurobot does not exist';
    END IF;
END;
$BODY$;

-- ---------------------------------------------------------------------------
-- 1. Enums
--    service_status        the admin-controlled publishing state.
--    service_contact_type  tells the frontend how to render/link a contact.
--                          `platform` stays free text (see service_contacts),
--                          so adding a new social network needs no migration.
-- ---------------------------------------------------------------------------
DO $BODY$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type WHERE typname = 'service_status' AND typtype = 'e'
    ) THEN
        CREATE TYPE service_status AS ENUM ('draft', 'published', 'hidden', 'archived');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_type WHERE typname = 'service_contact_type' AND typtype = 'e'
    ) THEN
        CREATE TYPE service_contact_type AS ENUM ('phone', 'email', 'url', 'username', 'other');
    END IF;
END;
$BODY$;

-- ---------------------------------------------------------------------------
-- 2. Categories (self-referential tree)
--    ON DELETE RESTRICT on the self reference means a parent with children
--    cannot be deleted. service_categories also RESTRICTs, so an assigned
--    category cannot be deleted either; deactivate with is_active instead.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     bigint REFERENCES public.categories (id) ON DELETE RESTRICT,
    name          text NOT NULL,
    slug          text NOT NULL,
    description   text,
    display_order integer NOT NULL DEFAULT 0,
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT categories_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_slug
    ON public.categories (slug);

CREATE INDEX IF NOT EXISTS ix_categories_parent_id
    ON public.categories (parent_id);

-- ---------------------------------------------------------------------------
-- 3. Services
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.services (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Optional owner. SET NULL so a listing survives its owner being removed.
    owner_user_id   bigint REFERENCES public.users_eurobot (user_id) ON DELETE SET NULL,
    -- Whether the owner relationship may be shown publicly. Defaults to FALSE:
    -- associating a user with a service must never, by itself, expose that
    -- relationship. An admin (or a future owner-management flow) must turn it on
    -- deliberately. Public display also requires the owner's own privacy
    -- settings to allow it; that check belongs to the read layer, not here.
    show_owner      boolean NOT NULL DEFAULT false,

    name            text NOT NULL,
    description     text,

    -- Independent Persian/Iranian relevance signals. They are deliberately
    -- separate facts, not one is_iranian flag.
    persian_owned    boolean NOT NULL DEFAULT false,
    persian_language boolean NOT NULL DEFAULT false,
    persian_service  boolean NOT NULL DEFAULT false,

    -- Structured location: participates in search, so it is not a contact row.
    address         text,
    postal_code     text,
    city            text,
    country         text,
    latitude        double precision,
    longitude       double precision,
    CONSTRAINT services_latitude_range
        CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
    CONSTRAINT services_longitude_range
        CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180)),

    status          service_status NOT NULL DEFAULT 'draft',

    -- Provenance for externally imported listings. Manually entered services
    -- may leave both null.
    source          text,
    external_id     text,

    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_services_status
    ON public.services (status);

CREATE INDEX IF NOT EXISTS ix_services_city
    ON public.services (city);

CREATE INDEX IF NOT EXISTS ix_services_owner_user_id
    ON public.services (owner_user_id);

-- Stable external identity for idempotent imports. Scoped to rows that carry
-- both values, so multiple manual rows (both null) never collide, and NULL
-- is never treated as a duplicate.
CREATE UNIQUE INDEX IF NOT EXISTS ux_services_source_external_id
    ON public.services (source, external_id)
    WHERE source IS NOT NULL AND external_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 4. Service <-> category (many-to-many, exactly one primary per service)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.service_categories (
    service_id  bigint NOT NULL REFERENCES public.services (id) ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES public.categories (id) ON DELETE RESTRICT,
    is_primary  boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (service_id, category_id)
);

-- At most one primary category per service, enforced by the database.
CREATE UNIQUE INDEX IF NOT EXISTS ux_service_categories_primary
    ON public.service_categories (service_id)
    WHERE is_primary;

CREATE INDEX IF NOT EXISTS ix_service_categories_category_id
    ON public.service_categories (category_id);

-- ---------------------------------------------------------------------------
-- 5. Service contacts (generic, ordered, optionally hidden)
--    platform is free text on purpose: unknown networks must not require a
--    schema migration. Icons/design assets are the frontend's job and are not
--    stored here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.service_contacts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id    bigint NOT NULL REFERENCES public.services (id) ON DELETE CASCADE,
    title         text NOT NULL,
    type          service_contact_type NOT NULL,
    value         text NOT NULL,
    platform      text,
    display_order integer NOT NULL DEFAULT 0,
    is_visible    boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_service_contacts_service_id
    ON public.service_contacts (service_id);

COMMENT ON TABLE public.categories IS
    'Hierarchical categories for service-directory listings';
COMMENT ON TABLE public.services IS
    'Service/business directory listings; owner is optional and may be hidden';
COMMENT ON TABLE public.service_categories IS
    'Many-to-many service<->category link; at most one is_primary per service';
COMMENT ON TABLE public.service_contacts IS
    'Flexible per-service contact methods; platform is free text';

COMMIT;
